<a href="https://colab.research.google.com/github/RiturajSaha/Diabetes-Prediction/blob/master/diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# cd "/content/drive/My Drive/Colab Notebooks/Diabetes Prediction"

/content/drive/My Drive/Colab Notebooks/Diabetes Prediction


Importing the Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing the Dataset

In [2]:
dataset=pd.read_csv("diabetes.csv")
newdataset=dataset
x=newdataset.iloc[:,0:8]
y=newdataset.iloc[:,-1]

Splitting the dataset into the Training set and Test set

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2,random_state = 0)
print("X_train:",len(X_train))
print("X_test:",len(X_test))
print("y_train:",len(y_train))
print("y_test:",len(y_test))

X_train: 614
X_test: 154
y_train: 614
y_test: 154


Classification Models

K Nearest Neighbor

In [4]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
KNN_model = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
KNN_model.fit(X_train, y_train)

# Predicting the Test set results
y_pred = KNN_model.predict(X_test)


# Analyzing the output
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error,accuracy_score,confusion_matrix,classification_report 
print("R2 Score:",r2_score(y_test, y_pred)) 
print("Mean Squared Error:",mean_squared_error(y_test, y_pred))
print("Mean Absolute Error:",mean_absolute_error(y_test, y_pred))
print("Accuracy:",accuracy_score(y_test, y_pred)*100) 
print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred))
print("Classification Report:\n",classification_report(y_test, y_pred)) 

R2 Score: -0.16365082521376006
Mean Squared Error: 0.24675324675324675
Mean Absolute Error: 0.24675324675324675
Accuracy: 75.32467532467533
Confusion Matrix:
 [[87 20]
 [18 29]]
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.81      0.82       107
           1       0.59      0.62      0.60        47

    accuracy                           0.75       154
   macro avg       0.71      0.72      0.71       154
weighted avg       0.76      0.75      0.75       154



Naive Bayes

In [7]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
NB_model = GaussianNB()
NB_model.fit(X_train, y_train)


# Predicting the Test set results
y_pred = NB_model.predict(X_test)


# Analyzing the output
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error,accuracy_score,confusion_matrix,classification_report 
print("R2 Score:",r2_score(y_test, y_pred)) 
print("Mean Squared Error:",mean_squared_error(y_test, y_pred))
print("Mean Absolute Error:",mean_absolute_error(y_test, y_pred))
print("Accuracy:",accuracy_score(y_test, y_pred)*100) 
print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred))
print("Classification Report:\n",classification_report(y_test, y_pred)) 

R2 Score: 0.020083515609465197
Mean Squared Error: 0.2077922077922078
Mean Absolute Error: 0.2077922077922078
Accuracy: 79.22077922077922
Confusion Matrix:
 [[93 14]
 [18 29]]
Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.87      0.85       107
           1       0.67      0.62      0.64        47

    accuracy                           0.79       154
   macro avg       0.76      0.74      0.75       154
weighted avg       0.79      0.79      0.79       154



Random Forest Classification

In [8]:
# Fitting Random Forest Classification to the Training set
from sklearn.ensemble import RandomForestClassifier
RFC_model = RandomForestClassifier(n_estimators = 1000, criterion = 'entropy')
RFC_model.fit(X_train, y_train)


# Predicting the Test set results
y_pred = KNN_model.predict(X_test)


# Analyzing the output
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error,accuracy_score,confusion_matrix,classification_report 
print("R2 Score:",r2_score(y_test, y_pred)) 
print("Mean Squared Error:",mean_squared_error(y_test, y_pred))
print("Mean Absolute Error:",mean_absolute_error(y_test, y_pred))
print("Accuracy:",accuracy_score(y_test, y_pred)*100) 
print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred))
print("Classification Report:\n",classification_report(y_test, y_pred)) 

R2 Score: -0.16365082521376006
Mean Squared Error: 0.24675324675324675
Mean Absolute Error: 0.24675324675324675
Accuracy: 75.32467532467533
Confusion Matrix:
 [[87 20]
 [18 29]]
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.81      0.82       107
           1       0.59      0.62      0.60        47

    accuracy                           0.75       154
   macro avg       0.71      0.72      0.71       154
weighted avg       0.76      0.75      0.75       154



Linear Support Vector Classification

In [9]:
# Fitting LinearSVC to the Training set
from sklearn.svm import LinearSVC
LSVC_model = LinearSVC()
LSVC_model.fit(X_train, y_train)


# Predicting the Test set results
y_pred = LSVC_model.predict(X_test)


# Analyzing the output
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error,accuracy_score,confusion_matrix,classification_report 
print("R2 Score:",r2_score(y_test, y_pred)) 
print("Mean Squared Error:",mean_squared_error(y_test, y_pred))
print("Mean Absolute Error:",mean_absolute_error(y_test, y_pred))
print("Accuracy:",accuracy_score(y_test, y_pred)*100) 
print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred))
print("Classification Report:\n",classification_report(y_test, y_pred)) 

R2 Score: -0.6229866772718233
Mean Squared Error: 0.34415584415584416
Mean Absolute Error: 0.34415584415584416
Accuracy: 65.5844155844156
Confusion Matrix:
 [[81 26]
 [27 20]]
Classification Report:
               precision    recall  f1-score   support

           0       0.75      0.76      0.75       107
           1       0.43      0.43      0.43        47

    accuracy                           0.66       154
   macro avg       0.59      0.59      0.59       154
weighted avg       0.65      0.66      0.65       154



c:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Support Vector Classification

In [10]:
# Fitting SVC to the Training set
from sklearn.svm import SVC
SVC_model = SVC(kernel = 'linear')
SVC_model.fit(X_train, y_train)


# Predicting the Test set results
y_pred = SVC_model.predict(X_test)


# Analyzing the output
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error,accuracy_score,confusion_matrix,classification_report 
print("R2 Score:",r2_score(y_test, y_pred)) 
print("Mean Squared Error:",mean_squared_error(y_test, y_pred))
print("Mean Absolute Error:",mean_absolute_error(y_test, y_pred))
print("Accuracy:",accuracy_score(y_test, y_pred)*100) 
print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred))
print("Classification Report:\n",classification_report(y_test, y_pred)) 

R2 Score: 0.14257307615828196
Mean Squared Error: 0.18181818181818182
Mean Absolute Error: 0.18181818181818182
Accuracy: 81.81818181818183
Confusion Matrix:
 [[97 10]
 [18 29]]
Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.91      0.87       107
           1       0.74      0.62      0.67        47

    accuracy                           0.82       154
   macro avg       0.79      0.76      0.77       154
weighted avg       0.81      0.82      0.81       154



Saving the model having highest Accuracy

In [14]:
import pickle
pickle.dump(SVC_model, open('SVC_model3.pkl','wb')) 

Sample Test

In [15]:
model = pickle.load(open('SVC_model3.pkl','rb'))
print("Diabetic" if model.predict([[6,148,72,35,0,33.6,0.627,50]])[0]==1 else "Normal")

Diabetic


c:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
